name: Vavoo IPTV Otomatik Guncelleme

on:
  schedule:
    # Her gün gece 00:00'da otomatik çalışır (UTC zaman dilimine göre)
    - cron: '0 0 * * *'
  workflow_dispatch: # İstediğiniz zaman GitHub panelinden elle başlatabilmeniz için

jobs:
  vavoo-update-job:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla (Checkout)
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Bağımlılıkları Kur (Gerekliyse)
      run: |
        python -m pip install --upgrade pip
        # Eğer betiğinizde requests, requests_html gibi kütüphaneler varsa alt satırdaki simgeyi (#) kaldırıp ekleyebilirsiniz:
        # pip install requests

    - name: Vavoo Betigini Calistir
      run: python vavoo_guncelle.py

    - name: Degisiklikleri Kaydet ve Push Et
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        # Eğer değişiklik yoksa hata vermemesi için kontrol ekliyoruz
        git diff --quiet && git diff --staged --quiet || (git commit -m "Vavoo kanalları otomatik güncellendi" && git push)
