name: Vavoo M3U Otomatik Guncelleme

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Kodlari Cek
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Kutuphaneleri Yukle
      run: pip install requests

    - name: Scripti Calistir
      run: python vavoo_guncelle.py

    - name: Degisiklikleri Otomatik Yukle
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Otomatik Vavoo M3U Guncellendi"
        file_pattern: "./vavoo_listem.m3u"
