name: Vavoo M3U Otomatik Guncelleme

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Kodlari Cek
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Scripti Calistir
      run: python vavoo_guncelle.py

    - name: Degisiklikleri Sunucuya Yukle
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add belgesel
        git commit -m "Otomatik Vavoo M3U Guncellendi" || exit 0
        git push origin main

