name: Update YouTube Stream Links

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu Çek
        uses: actions/checkout@v4

      - name: Python Ortamını Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli Paketleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp streamlink

      - name: Güncelleme Betiğini Çalıştır
        run: python update_playlist.py

      - name: Değişiklikleri GitHub'a Push Et
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add boncuk
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update stream links" && git push)
